/*
 * Shape Menu Program (Final Version)
 * Features: Heart, Exclamation Mark, Arrow Animation
 * Author: Xiao Fu AI Assistant
 * Date: 2026-03-09
 */

#include <iostream>
#include <string>
#include <cmath>
#include <limits>
#include <vector>

// Cross-platform support
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

using namespace std;

// ============== Utility Functions ==============

/**
 * Clear screen - cross-platform
 */
void clearScreen() {
#ifdef _WIN32
    system("cls");
#else
    system("clear");
#endif
}

/**
 * Sleep function - cross-platform
 */
void sleepMs(int milliseconds) {
#ifdef _WIN32
    Sleep(milliseconds);
#else
    usleep(milliseconds * 1000);
#endif
}

/**
 * Pause and wait for Enter key
 */
void pause() {
    cout << "\nPress Enter to continue...";
    cin.ignore(numeric_limits<streamsize>::max(), '\n');
    cin.get();
}

// ============== Shape Display Functions ==============

/**
 * Display heart shape (generated by mathematical formula)
 * @param height Height of the heart (number of lines)
 */
void showHeart(int height) {
    if (height < 5) {
        height = 5;  // minimum height
    }
    if (height > 40) {
        height = 40;  // maximum height
    }

    cout << "\n\n";

    // Use heart parametric equation to generate
    // x = 16 * sin^3(t)
    // y = 13 * cos(t) - 5 * cos(2t) - 2 * cos(3t) - cos(4t)

    vector<string> lines;
    for (int i = 0; i < height * 2; i++) {
        lines.push_back(string(height * 3, ' '));
    }

    // Generate heart points
    for (double t = 0; t < 2 * M_PI; t += 0.05) {
        double x = 16 * pow(sin(t), 3);
        double y = 13 * cos(t) - 5 * cos(2 * t) - 2 * cos(3 * t) - cos(4 * t);

        // Scale and flip
        int scale = height / 20;  // scale factor
        if (scale < 1) scale = 1;

        int px = int(x * scale) + height * 1.5;
        int py = int(-y * scale) + height;

        if (py >= 0 && py < (int)lines.size() && px >= 0 && px < (int)lines[0].length()) {
            lines[py][px] = '*';
        }
    }

    // Fill heart (make it fuller)
    for (int i = 0; i < (int)lines.size(); i++) {
        string &line = lines[i];
        int left = line.find('*');
        int right = line.rfind('*');

        if (left != string::npos && right != string::npos) {
            for (int j = left; j <= right; j++) {
                line[j] = '*';
            }
        }
    }

    // Output heart
    for (const auto &line : lines) {
        cout << line << "\n";
    }

    cout << "\n";
}

/**
 * Display exclamation mark
 * Thick vertical line + thick rectangle base
 */
void showExclamation() {
    cout << "\n\n";

    int width = 9;   // width
    int height = 10; // vertical line height

    // Vertical line part
    for (int i = 0; i < height; i++) {
        string line(width, '*');
        cout << "     " << line << "\n";
    }

    cout << "\n";  // empty line

    // Base (thick rectangle)
    for (int i = 0; i < 2; i++) {
        string line(width, '*');
        cout << "     " << line << "\n";
    }

    cout << "\n";
}

/**
 * Display arrow animation
 * Single line arrow, moves from left to right
 */
void showMovingArrow() {
    const int MAX_STEPS = 50;
    const int DELAY_MS = 50;
    const int ARROW_LENGTH = 10;

    // Move from left to right
    for (int i = 0; i < MAX_STEPS; i++) {
        clearScreen();

        string spaces(i, ' ');
        string arrow(ARROW_LENGTH, '-');
        string arrowHead = spaces + arrow + ">";

        cout << "\n\n\n\n";
        cout << "      " << arrowHead << "\n";

        cout << "\n\n";
        cout << "Arrow moving from left to right... (" << i + 1 << "/" << MAX_STEPS << ")\n";

        sleepMs(DELAY_MS);
    }

    clearScreen();
    cout << "\n\nArrow movement completed!\n\n";
}

// ============== Menu Functions ==============

/**
 * Display menu
 */
void showMenu() {
    cout << "\n";
    cout << "=================================\n";
    cout << "       Shape Display Menu\n";
    cout << "=================================\n";
    cout << "\n";
    cout << "    1. Heart (adjustable size)\n";
    cout << "    2. Exclamation Mark\n";
    cout << "    3. Arrow Animation\n";
    cout << "    0. Exit Program\n";
    cout << "\n";
    cout << "=================================\n";
    cout << "Enter your choice (0-3): ";
}

// ============== Main Program ==============

int main() {
    int choice;
    int height;

    // Set console encoding (Windows)
#ifdef _WIN32
    system("chcp 65001 > nul");
#endif

    // Main loop
    while (true) {
        showMenu();
        cin >> choice;

        // Clear input buffer
        cin.ignore(numeric_limits<streamsize>::max(), '\n');

        switch (choice) {
            case 1:
                clearScreen();
                cout << "\n>>> You chose: Heart\n";
                cout << "\nEnter heart height (lines, recommended 10-30): ";
                cin >> height;
                cin.ignore(numeric_limits<streamsize>::max(), '\n');
                showHeart(height);
                break;

            case 2:
                clearScreen();
                cout << "\n>>> You chose: Exclamation Mark\n";
                showExclamation();
                break;

            case 3:
                clearScreen();
                cout << "\n>>> You chose: Arrow Animation\n";
                showMovingArrow();
                break;

            case 0:
                clearScreen();
                cout << "\n";
                cout << "=================================\n";
                cout << "     Thank you, goodbye!\n";
                cout << "=================================\n";
                cout << "\n";
                return 0;

            default:
                clearScreen();
                cout << "\n";
                cout << "=================================\n";
                cout << "      Invalid choice!\n";
                cout << "=================================\n";
                cout << "\n";
                cout << "Please enter a number between 0-3.\n";
                break;
        }

        // Wait for user
        pause();
        clearScreen();
    }

    return 0;
}